# Generated by Django 2.1.5 on 2019-01-10 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('format', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=225)),
                ('update_rate', models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Min. Update Interval [sec]')),
                ('max_range', models.DecimalField(decimal_places=3, default=1, max_digits=15)),
                ('min_range', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('actuator', models.BooleanField(blank=True, default=False)),
                ('protocol', models.CharField(blank=True, max_length=255, verbose_name='Protocol')),
                ('image_url', models.URLField(blank=True)),
                ('callibration', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('transducer_type', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='localhost', max_length=255, verbose_name='Name')),
                ('address', models.GenericIPAddressField(default='127.0.0.1', verbose_name='Address')),
                ('port', models.IntegerField(default=8000, verbose_name='Port')),
                ('protocol', models.CharField(blank=True, default='http', max_length=255, verbose_name='Protocol')),
                ('url', models.URLField(blank=True)),
                ('mac_address', models.CharField(blank=True, max_length=75)),
                ('active', models.BooleanField(default=True)),
                ('process_name', models.CharField(blank=True, max_length=255, verbose_name='Process Name')),
                ('process_pid', models.IntegerField(blank=True, default=0, verbose_name='PID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_from_gateway_only', models.BooleanField(default=False)),
                ('update_rate', models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Min. Update Interval [sec]')),
                ('update_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Min. change in value to accept update')),
                ('active', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Serial Number')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.Device')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.DeviceGateway')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('devices', models.ManyToManyField(to='sensordata.DeviceInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(default='None')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('x_absolute', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('y_absolute', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('z_absolute', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('reference_description', models.TextField(blank=True)),
                ('x_reference', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('y_reference', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('z_reference', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=150)),
                ('url', models.URLField(blank=True, max_length=750)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Note', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(default='None', max_length=25)),
                ('signal_description', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('measurement_timestamp', models.DateTimeField()),
                ('measurement_timestamp_sec', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=25)),
                ('symbol', models.CharField(blank=True, max_length=30)),
                ('system', models.CharField(blank=True, max_length=8)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.Location'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensordata.Location'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='physical_signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.PhysicalSignal'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_instance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.Manufacturer'),
        ),
        migrations.AddField(
            model_name='device',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.Units'),
        ),
        migrations.AddField(
            model_name='datavalue',
            name='data_timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.TimeStamp'),
        ),
        migrations.AddField(
            model_name='datavalue',
            name='device_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.DeviceInstance'),
        ),
        migrations.AddField(
            model_name='dataobject',
            name='data_timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.TimeStamp'),
        ),
        migrations.AddField(
            model_name='dataobject',
            name='device_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.DeviceInstance'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('device_name', 'model_number')},
        ),
    ]
